/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as LocationRouteImport } from './routes/location'
import { Route as MembershipRouteImport } from './routes/membership'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as TimingsRouteImport } from './routes/timings'
import { Route as TrainersRouteImport } from './routes/trainers'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationRoute = LocationRouteImport.update({
  id: '/location',
  path: '/location',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipRoute = MembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const TimingsRoute = TimingsRouteImport.update({
  id: '/timings',
  path: '/timings',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainersRoute = TrainersRouteImport.update({
  id: '/trainers',
  path: '/trainers',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/location': typeof LocationRoute
  '/membership': typeof MembershipRoute
  '/services': typeof ServicesRoute
  '/timings': typeof TimingsRoute
  '/trainers': typeof TrainersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/location': typeof LocationRoute
  '/membership': typeof MembershipRoute
  '/services': typeof ServicesRoute
  '/timings': typeof TimingsRoute
  '/trainers': typeof TrainersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/location': typeof LocationRoute
  '/membership': typeof MembershipRoute
  '/services': typeof ServicesRoute
  '/timings': typeof TimingsRoute
  '/trainers': typeof TrainersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/location'
    | '/membership'
    | '/services'
    | '/timings'
    | '/trainers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/location'
    | '/membership'
    | '/services'
    | '/timings'
    | '/trainers'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/location'
    | '/membership'
    | '/services'
    | '/timings'
    | '/trainers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  LocationRoute: typeof LocationRoute
  MembershipRoute: typeof MembershipRoute
  ServicesRoute: typeof ServicesRoute
  TimingsRoute: typeof TimingsRoute
  TrainersRoute: typeof TrainersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/location': {
      id: '/location'
      path: '/location'
      fullPath: '/location'
      preLoaderRoute: typeof LocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership': {
      id: '/membership'
      path: '/membership'
      fullPath: '/membership'
      preLoaderRoute: typeof MembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timings': {
      id: '/timings'
      path: '/timings'
      fullPath: '/timings'
      preLoaderRoute: typeof TimingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainers': {
      id: '/trainers'
      path: '/trainers'
      fullPath: '/trainers'
      preLoaderRoute: typeof TrainersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  LocationRoute: LocationRoute,
  MembershipRoute: MembershipRoute,
  ServicesRoute: ServicesRoute,
  TimingsRoute: TimingsRoute,
  TrainersRoute: TrainersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
